Wizard101_Trivia = {
    "Which of these are not a Lore spell?":"Fire Dragon",
    "Which of these is NOT a Zafaria Anchor Stone?":"Rasik Anchor Stone",
    "Shaka Zebu is known best as:":"The Greatest Living Zebra Warrior",
    "What is the name of the book stolen from the Royal Museum?":"The Krokonomicon",
    "Who is the Bear King of Grizzleheim?":"Valgard Goldenblade",
    "What type of rank 8 spell is taught to Death students at level 58?":"Damage + DoT",
    "An unmodified Sun Serpent does what?":"900�1000 Fire damage + 300 Fire damage to all enemies",
    "What does the Time Ribbon protect against?":"Time Flux",
    "Which Aztecan ponders the Great Questions of Life?":"Philosoraptor",
    "How long do you have to wait to join a new match after fleeing in PVP?":"5 Minutes",
    "What hand does Lady Oriel hold her wand in?":"Trick question, she has a sword",
    "What is Professor Falmea's favorite food?":"Pasta Arrabiata",
    "What determines the colors of the Manders in Krokotopia?":"Where they come from and their school of focus",
    "In Grizzleheim, the Ravens want to bring about what?":"The Everwinter, to cover the world in ice",
    "What is the name of the secret society in Krokotopia?":"Order of the Fang",
    "Who is in the top level of the Tower of the Helephant?":"Lyon Lorestriker",
    "What school is the Gurtok Demon focused on?":"Balance",
    "What is unique about Falmea's classroom?":"There are scorch marks on the ceiling",
    "What is the name of the new dance added with Khrysalis?":"The Bee Dance",
    "What school is the spell Dark Nova?":"Shadow",
    "What book was Anna Flameright accused of stealing?":"Advanced Flameology",
    "Sir Edward Halley is the Spiral's most famous what?":"Aztecasaurologist",
    "Who is NOT a member of the Council of Light?":"Cyrus Drake",
    "What is the shape on the weather vanes in the shopping district?":"Half moon/moon",
    "Kirby Longspear was once a student of which school of magic?":"Death",
    "The Swordsman Destreza was killed by:":"A Gorgon",
    "How many portal summoning candles are in the Burial Mound?":"Three",
    "What did Abigail Doolittle accuse Wadsworth of stealing?":"Imitation Golden Ruby",
    "What was the name of the powerful Grendel Shaman who sealed the runic doors?":"Thulinn",
    "What level must you be to wear Dragonspyre crafted clothing?":"33",
    "Which Queen is mentioned in the Marleybone book “The Golden Age”?":"Ellen",
    "Who is the King of the Burrowers?":"Pyat MourningSword",
    "Who is Bill Tanner's sister?":"Sarah Tanner",
    "Which one of these is not a symbol on the battle sigil?":"Wand",
    "What color is the door inside the boys' dormroom?":"Red",
    "Zafaria is home to what cultures?":"Gorillaz, Zebras, Lions",
    "Which below are NOT a type of Oni in Mooshu?":"Ruby",
    "Why are the Gobblers so afraid to go home?":"Witches",
    "What's the name of the Balance tree?":"Niles",
    "What is the only school left standing in Dragonspyre?":"Fire",
    'Who prophesizes this: “The mirror will break, the horn will call, from the shadows I strike, and the skies will fall…”':"Morganthe",
    "Why are the pixies and faeries on Unicorn Way evil?":"Rattlebones corrupted them",
    "What can be used to diminish the Nirini's powers in Krokotopia?":"Flame Gems",
    "What is the shape of the pink piece in Potion Motion?":"Heart",
    "How many worlds of the spiral are unlocked as of May 21st, 2014?":"12",
    "Who is the registrar of Pigswick Academy?":"Mrs. Dowager",
    "Merle Ambrose is originally from which world?":"Avalon",
    "Who sells Valentine's Day items in Wizard City?":"Valentina Heartsong",
    "Who is the Nameless Knight?":"Sir Malory",
    "What did Prospector Zeke lose track of in Mooshu":"Blue Oysters",
    "What is the title of the book floating around the Wizard City Library?":"Basic Wizarding & Proper Care of Familiars",
    "Which of these locations is not in Wizard City?":"Digmoore Station",
    "Who guards the entrance to Unicorn Way?":"Private Stillson",
    "What book does Professor Drake send you to the library to check out?":"Book on the Wumpus",
    "What course did Herold Digmoore study?":"Ancient Myths for Parliament",
    "What did Prospector Zeke lose in Marleybone?":"The Stray Cats",
    "What initials were on the doctor's glove?":"XX",
    "What is a very common last name of the cats in Marleybone?":"O'Leary",
    "What transports you from place to place in Marleybone?":"Hot Air Balloons",
    "What symbol is not on the stained glass window in Regent's Square?":"A Tennis Ball",
    "Which is not a street in Regent's Square?":"Fleabitten Ave",
    "What is flying around in Regent's Square?":"Newspapers",
    "What sort of beverage is served in Air Dales Hideaway?":"Root Beer",
    "What is Sgt. Major Talbot's full name?":"Sylvester Quimby Talbot III",
    "WWho is the dangerous criminal that is locked up, but escapes from Newgate Prison?":"Meowiarty",
    "Who is not an officer you'll find around Marleybone?":"Officer Digmore",
    "What time of day is it always in Marleybone?":"Night",
    "What style of artifacts are in the Royal Museum?":"Krokotopian",
    "What two names are on the Statues in the Marleybone cathedral?":"Saint Bernard and Saint Hubert",
    "Arthur Wethersfield is A:..":"Dog",
    "What time does the clock always read in Marleybone?":"1:55",
    "Which symbol is not on the stained glass window in Regent's Square?":" A Tennis Ball",
    "What event is Abigail Doolittle sending out invitations for?":"The Policeman's Ball",
    "What color are the Marleybone mailboxes?":"Red",
    "Which of these folks can you find in the Royal Museum?":"Clancy Pembroke",
    "Who tells you how to get to Aquila?":"Harold Argleston",
    "What is used to travel to the Isle of Arachnis?":"Ice Archway",
    "King Axaya Knifemoon needs what to unify the people around him?":"The Badge of Leadership",
    "King Neza is Zenzen Seven Star's..":"Grandfather",
    "What was Ponce de Gibbon looking for in Azteca?":"The Water of Life",
    "Hrundle Fjord is part of what section of Grizzleheim?":"Wintertusk",
    "Who is the only person who knows how to enter the Tomb of Storms?":"Hetch Al'Dim",
    "Who gives you permission to ride the boat to the Krokosphinx?":"Sergeant Major Talbot",
    "Who takes you across the River of Souls?":"Charon",
    "In Regent's Square, the Professor is standing in front of a…":"Telegraph Box",
    "Which villain terrorizes the fair maidens of Marleybone?":"Jaques the Scratcher",
    "Thaddeus Price is the Pigswick Academy Professor of what school?":"Tempest",
    "Who was the Greatest Aquilian Gladiator of all time?":"Dimachaerus",
    "In what world would you find the Spider Temple?":"Zafaria",
    "Who is the Emperor of Mooshu's Royal Guard?":"Noboru Akitame",
    "Who asks you to find Khrysanthemums?":"Eloise Merryweather",
    "Who did Falynn Greensleeves fall in love with?":"Sir Malick de Logres",
    "Who haunts the Night Warrens?":"Nosferabbit",
    "Where is the only pure fire in the Spiral found?":"Wizard City",
    "Who was ordered to guard the Sword of Kings?":"The Knights of the Silver Rose",
    "Who helps Morganthe find the Horn of Huracan?":"Belloq",
    "Who thinks you are there to take their precious feathers?":"Takeda Kanryu",
    'Who taunts you with: “Wizard, you will know the meaning of the word pain after we battle!”':"Aiuchi",
    "Where has Pharenor been imprisoned?":"Skythorn Tower",
    "Who tries to raise a Gorgon Army?":"Phorcys",
    "Sumner Fieldgold twice asks you to recover what for him?":"Shrubberies",
    'Who tells you: “A shield is just as much a weapon as the sword.”':"Mavra Flamewing",
    "Who is Haraku Yip's apprentice?":"Binh Hoa",
    "Morganthe got the Horned Crown from the Spriggan:":"Gisela",
    "Who grants the first Shadow Magic spell?":"Sophia DarkSide",
    "The Swallows of Caliburn migrate to Avalon from where each year?":"Zafaria and Marleybone",
    "In Azteca, Morganthe enlisted the help of the:":"The Black Sun Necromancers",
    "Who makes the harpsicord for Shelus?":"Gretta Darkkettle",
    "What badge do you earn by defeating 100 Samoorai?":"Yojimbo",
    "What special plant was Barley developing in his Garden?":"Cultivated Woodsmen",
    "Who taunts: Why I oughta knock you to the moon, you pesky little creep!":"Mugsy",
    "What does Silenus name you once you've defeated Hades?":"Glorious Golden Archon",
    "Who needs the healing potion from Master Yip?":"Binh Hoa",
    'Who taunts you with: “Prepare to be broken, kid!”':"Clanker",
    'Who tells you to speak these words only unto your mentor: “Meena Korio Jajuka!”':"Priya the Dryad",
    "Who teaches you Balance magic?":"Alhazred",
    "What term best fits Star Magic Spells?":"Auras",
    "How many pips does it cost to cast Dr. Von's Monster?":"9",
    "Which spell can't be cast while polymorphed as a Gobbler?":"Pie in the sky",
    "What term best fits Sun Magic Spells?":"Enchantment",
    "What type of spells are Ice, Fire, and Storm?":"Elemental",
    "Which spell would not be very effective when going for the elixir vitae Badge?":"Entangle",
    "What level of spell does Enya Firemoon Teach?":"80",
    "Which Fire spell both damages and heals over time?":"Power Link",
    "Mildred Farseer teaches you what kind of spell?":"Dispels",
    "How many pips does it cost to cast Stormzilla?":"5",
    "Cassie the Ponycorn teaches this kind of spell:":"Prisms",
    "If you can cast Storm Trap, Wild Bolt, Catalan, and the Tempest spell, what are you polymorphed as?":"Ptera",
    "Cassie the Ponycorn teaches this kind of spell":"Prism",
    "If you're a storm wizard with 4 power pips and 3 regular pips, how powerful would your supercharge charm be?":"110%",
    "Mortis can teach you this.":"Tranquilize.",
    "Tish'Mah specializes in spells that mostly affect these:":"Minions",
    "Ether Shield protects against what?":"Life and Death attacks",
    "What isn't a shadow magic spell?":"Ebon Ribbons",
    "Who can teach you the Life Shield Spell?":"Sabrina Greenstar",
    "What does Forsaken Banshee do?":"375 damage plus a hex trap",
    "Who sang the Dragons, Titans and Giants into existance?":"Bartleby",
    "Where is Sabrina Greenstar?":"Fairgrounds",
    "What is the name of the school newspaper Boris Tallstaff knows?":"Ravenwood Bulletin",
    "What is the name of the bridge in front of the Cave to Nightside?":"Rainbow Bridge",
    "What are the school colors of Balance?":"Tan and Maroon",
    "Who is the Wizard City mill foreman?":"Sohomer Sunblade",
    "Who taught Life Magic before Moolinda Wu?":"Sylvia Drake",
    "Who is the fire school professor?":"Dalia Falmea",
    "What is the name of the Ice Tree in Ravenwood?":"Kelvin",
    "What are the main colors for the myth school?":"Blue and Gold Correct!",
    "Who sang the Dragons, Titans and Giants into existance?":"Bartleby",
    "Who is the Princess of the Seraphs?":"Lady Oriel",
    "What school is all about Creativity?":"Storm",
    "What is the name of the Grandfather Tree?":"Bartleby",
    "What does every rotting fodder in the dark caves carry with them?":"A Spade",
    "What is something that the gobblers are NOT stockpiling in Colossus Way?":"Broccoli",
    "What is the gemstone for Balance?":"Citrine",
    "What school does Malorn Ashthorn think is the best?":"Death",
    "What is Mindy's last name (she's on Colossus Blvd)?":"Pixiecrown",
    "Who resides in the Hedge Maze?":"Lady Oriel",
    "What is Diego's full name?":"Diego Santiago Quariquez Ramirez the Third",
    "Vir Goodheart is an assistant to":"Rasik Pridefall",
    "Who are Hannibal Onetusk's brother and co-pilot?":"Mago and Sobaka",
    "Sir Reginal Baxby's cousin is:":"Mondli Greenhoof",
    "Jambo means:":"Hello.",
    "Baobab is governed by":"A Council of three councilors",
    "Zamunda's great assassin is known as":"Karl the Jackal",
    "Esop Thornpaw gives you a magic":"Djembe Drum",
    "Zebu Blackstripes legendary blade was forged":"In the halls of Valencia",
    "Unathi Nightrunner is":"A councilor of Baobab",
    "The Fire Lion Ravagers are led by":"Nergal the Burned Lion",
    "Who is the missing prince?":"Tiziri Silvertusk",
    "What does Lethu Blunthoof says about Ghostmanes?":"You can never tell with them!",
    "Umlilo Sunchaser hired who as a local guide?":"Msizi Redband",
    "Rasik Pridefall is":"An Olyphant from Stone Town.",
    "The Inzinzebu Bandits are harassing the good merchants in":"Baobab Market",
    "Koyate Ghostmane accuses the player of":"Being a thief",
    "Inyanga calls Umlio a":"Fire feather",
    "Zebu Blackstripes legendary blade was called":"The Sword of the Duelist",
    "Who is not one of the Zebu Kings":"Zaffe Zoffer",
    "Belloq is first found in":"The Sook",
    "Who reads the inscription on Marleybone's Tower?":"Ratbeard",
    "Where do you find the Tomb of Marco Pollo?":"Granchia",
    "What shows Steed you're part of the Resistence?":"Amulet",
    "Historian Gonzago is on a stage, who isn't in the audience?":"Giafra",
    "What are Albus and Carbo?":"Armada Commanders",
    "How many Mechanical Birds do you collect in Sivella?":"5",
    "Who do you find in the Lecture Hall of Sivella?":"Ridolfo",
    "Why does Steed want you to attack Armada Ships?":"Make a Disguise",
    "You won't find this kind of Armada Troop in Sivella!":"Battle Angel",
    "Historian Gonzago sends you on a “paper chase,” who do you talk to during that quest?":"Magdalena",
    "Which one isn't a Scholar by name?":"Lorenzo",
    "What color of Windstone do you find in Marco Pollo's Tomb?":"Blue",
    "Which one isn't a Scholar by name?":"Caresini",
    "Which world doesn't have a pillar in Sivella?":"Monquista",
    "What type of item does Prospector Zeke want you to find in Valencia?":"Birds",
    "You need a good eye to save these in Granchia…":"Art Objects",
    "Who does Steed send you to speak to in Sivella?":"Thaddeus",
    "What's the name of a librarian in Sivella?":"Grassi",
    "The Mooshu Tower in Sivella is a replica of what?":"Tower of Serenity",
    "What type of boat do you use to get from the docks to Sivella?":"Gondola"
}
